sudo: required

services:
  - docker

language: python

script:
  - python -m pytest -v

after_success:
  jobs:
    include:
      - stage: build docker image
      - sh .travis/deploy_dockerhub.sh
      - stage: test
      - script: docker run --rm $DOCKER_USERNAME/cicd:latest cat hello.txt
      - script: docker run --rm $DOCKER_USERNAME/cicd:latest cat hello.txt

  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
  
notifications:
  slack: cicd-corp:dzYY3OOsirONb698ev6WXl9s