sudo: required

services:
  - docker

language: python

jobs:
  include:
    - stage: "Adding pytest"
      name: "Running unittests"
      script:
        - python -m pytest -v
    - stage: "pushing image"
      name: "Pushing image to DockerHub"
      script:
        - sh .travis/deploy_dockerhub.sh
    - stage: "pushing image"
      name: "Pushing image to Heroku"
      script:
        - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh

notifications:
  slack: cicd-corp:dzYY3OOsirONb698ev6WXl9s
