sudo: required

services:
  - docker

language: python

script:
  - python -m pytest -v

after_success:
  - sh .travis/deploy_dockerhub.sh

  deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app: $HEROKU_APP_NAME
  
notifications:
  slack: cicd-corp:dzYY3OOsirONb698ev6WXl9s