sudo: required

services:
  - docker

language: python

jobs:
  include:
    - stage: "Adding pytest"
      script:
      name: "Adding Pystest"
        - python -m pytest -v
    - stage: "pushing image"
      script:
      name: "Pushing image to DockerHub" 
        - sh .travis/deploy_dockerhub.sh
      name: "Pushing image to Heroku"
        - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh

notifications:
  slack: cicd-corp:dzYY3OOsirONb698ev6WXl9s
